version: "3"

services:

    web:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - 8080:80
        depends_on:
            - app
        container_name: mwapp-web

    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        depends_on:
            - db
        container_name: mwapp-app

    db:
        image: mysql:8.0-debian
        restart: always
        volumes:
            - ./tmp/db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: mwapp-mysql-db
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 8101:3306
        container_name: mwapp-db
